const ActionTypes = {
    ADD_CATEGORY: "ADD_CATEGORY",
    REMOVE_CATEGORY: "REMOVE_CATEGORY",
    EDIT_CATEGORY: "EDIT_CATEGORY",
    START_EDIT_CATEGORY: "START_EDIT_CATEGORY",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    EDIT_ITEM: "EDIT_ITEM",
    START_EDIT_ITEM: "START_EDIT_ITEM",
    FILTER_CATEGORY: "FILTER_CATEGORY"
};

export default ActionTypes;