const ActionTypes = {
    ADD_CATEGORY: "ADD_CATEGORY",
    REMOVE_CATEGORY: "REMOVE_CATEGORY",
    EDIT_CATEGORY: "EDIT_CATEGORY",
    START_EDIT_CATEGORY: "START_EDIT_CATEGORY"
};

export default ActionTypes;